"""add_show_in_nav_to_installed_plugins

Revision ID: 2fad1de52ebc
Revises: normalize_location_identifier
Create Date: 2026-03-13 23:21:28.705671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fad1de52ebc'
down_revision: Union[str, Sequence[str], None] = 'normalize_location_identifier'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filament_printer_params_filament'), table_name='filament_printer_params')
    op.drop_index(op.f('ix_filament_printer_params_printer'), table_name='filament_printer_params')
    op.create_index(op.f('ix_filament_printer_params_filament_id'), 'filament_printer_params', ['filament_id'], unique=False)
    op.create_index(op.f('ix_filament_printer_params_printer_id'), 'filament_printer_params', ['printer_id'], unique=False)
    op.add_column('installed_plugins', sa.Column('show_in_nav', sa.Boolean(), nullable=False, server_default='0'))
    op.drop_index(op.f('ix_spool_printer_params_printer'), table_name='spool_printer_params')
    op.drop_index(op.f('ix_spool_printer_params_spool'), table_name='spool_printer_params')
    op.create_index(op.f('ix_spool_printer_params_printer_id'), 'spool_printer_params', ['printer_id'], unique=False)
    op.create_index(op.f('ix_spool_printer_params_spool_id'), 'spool_printer_params', ['spool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spool_printer_params_spool_id'), table_name='spool_printer_params')
    op.drop_index(op.f('ix_spool_printer_params_printer_id'), table_name='spool_printer_params')
    op.create_index(op.f('ix_spool_printer_params_spool'), 'spool_printer_params', ['spool_id'], unique=False)
    op.create_index(op.f('ix_spool_printer_params_printer'), 'spool_printer_params', ['printer_id'], unique=False)
    op.drop_column('installed_plugins', 'show_in_nav')
    op.drop_index(op.f('ix_filament_printer_params_printer_id'), table_name='filament_printer_params')
    op.drop_index(op.f('ix_filament_printer_params_filament_id'), table_name='filament_printer_params')
    op.create_index(op.f('ix_filament_printer_params_printer'), 'filament_printer_params', ['printer_id'], unique=False)
    op.create_index(op.f('ix_filament_printer_params_filament'), 'filament_printer_params', ['filament_id'], unique=False)
    # ### end Alembic commands ###
