"""add indexes for performance

Revision ID: 8fa32fe633e5
Revises: c5d8f74c07af
Create Date: 2026-02-21 12:14:19.749974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa32fe633e5'
down_revision: Union[str, Sequence[str], None] = 'c5d8f74c07af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_filament_colors_color_id'), 'filament_colors', ['color_id'], unique=False)
    op.create_index(op.f('ix_filament_colors_filament_id'), 'filament_colors', ['filament_id'], unique=False)
    op.create_index(op.f('ix_filaments_designation'), 'filaments', ['designation'], unique=False)
    op.create_index(op.f('ix_filaments_manufacturer_id'), 'filaments', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_filaments_material_subgroup'), 'filaments', ['material_subgroup'], unique=False)
    op.create_index(op.f('ix_filaments_type'), 'filaments', ['type'], unique=False)
    op.create_index(op.f('ix_manufacturers_name'), 'manufacturers', ['name'], unique=True)
    op.create_index(op.f('ix_printer_slot_assignments_spool_id'), 'printer_slot_assignments', ['spool_id'], unique=False)
    op.create_index(op.f('ix_printer_slots_ams_unit_id'), 'printer_slots', ['ams_unit_id'], unique=False)
    op.create_index(op.f('ix_printer_slots_printer_id'), 'printer_slots', ['printer_id'], unique=False)
    op.create_index(op.f('ix_spool_statuses_key'), 'spool_statuses', ['key'], unique=True)
    op.create_index(op.f('ix_spools_deleted_at'), 'spools', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_spools_external_id'), 'spools', ['external_id'], unique=True)
    op.create_index(op.f('ix_spools_filament_id'), 'spools', ['filament_id'], unique=False)
    op.create_index(op.f('ix_spools_location_id'), 'spools', ['location_id'], unique=False)
    op.create_index(op.f('ix_spools_lot_number'), 'spools', ['lot_number'], unique=False)
    op.create_index(op.f('ix_spools_remaining_weight_g'), 'spools', ['remaining_weight_g'], unique=False)
    op.create_index(op.f('ix_spools_rfid_uid'), 'spools', ['rfid_uid'], unique=True)
    op.create_index(op.f('ix_spools_status_id'), 'spools', ['status_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spools_status_id'), table_name='spools')
    op.drop_index(op.f('ix_spools_rfid_uid'), table_name='spools')
    op.drop_index(op.f('ix_spools_remaining_weight_g'), table_name='spools')
    op.drop_index(op.f('ix_spools_lot_number'), table_name='spools')
    op.drop_index(op.f('ix_spools_location_id'), table_name='spools')
    op.drop_index(op.f('ix_spools_filament_id'), table_name='spools')
    op.drop_index(op.f('ix_spools_external_id'), table_name='spools')
    op.drop_index(op.f('ix_spools_deleted_at'), table_name='spools')
    op.drop_index(op.f('ix_spool_statuses_key'), table_name='spool_statuses')
    op.drop_index(op.f('ix_printer_slots_printer_id'), table_name='printer_slots')
    op.drop_index(op.f('ix_printer_slots_ams_unit_id'), table_name='printer_slots')
    op.drop_index(op.f('ix_printer_slot_assignments_spool_id'), table_name='printer_slot_assignments')
    op.drop_index(op.f('ix_manufacturers_name'), table_name='manufacturers')
    op.drop_index(op.f('ix_filaments_type'), table_name='filaments')
    op.drop_index(op.f('ix_filaments_material_subgroup'), table_name='filaments')
    op.drop_index(op.f('ix_filaments_manufacturer_id'), table_name='filaments')
    op.drop_index(op.f('ix_filaments_designation'), table_name='filaments')
    op.drop_index(op.f('ix_filament_colors_filament_id'), table_name='filament_colors')
    op.drop_index(op.f('ix_filament_colors_color_id'), table_name='filament_colors')
    # ### end Alembic commands ###
