"""Add cascading spool properties

Revision ID: 9a3956828c05
Revises: 052c2c33fca0
Create Date: 2026-02-22 13:22:44.160081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3956828c05'
down_revision: Union[str, Sequence[str], None] = '052c2c33fca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filaments', sa.Column('spool_outer_diameter_mm', sa.Float(), nullable=True))
    op.add_column('filaments', sa.Column('spool_width_mm', sa.Float(), nullable=True))
    op.add_column('filaments', sa.Column('spool_material', sa.String(length=100), nullable=True))
    op.add_column('manufacturers', sa.Column('empty_spool_weight_g', sa.Float(), nullable=True))
    op.add_column('manufacturers', sa.Column('spool_outer_diameter_mm', sa.Float(), nullable=True))
    op.add_column('manufacturers', sa.Column('spool_width_mm', sa.Float(), nullable=True))
    op.add_column('manufacturers', sa.Column('spool_material', sa.String(length=100), nullable=True))
    op.add_column('spools', sa.Column('spool_material', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spools', 'spool_material')
    op.drop_column('manufacturers', 'spool_material')
    op.drop_column('manufacturers', 'spool_width_mm')
    op.drop_column('manufacturers', 'spool_outer_diameter_mm')
    op.drop_column('manufacturers', 'empty_spool_weight_g')
    op.drop_column('filaments', 'spool_material')
    op.drop_column('filaments', 'spool_width_mm')
    op.drop_column('filaments', 'spool_outer_diameter_mm')
    # ### end Alembic commands ###
